### ISSUE TITLE
If Canvas App Explorer isn't launched from a course the API throws a 500 error

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#178]
I've noticed this error if you view the URL without being launched in a course.

We probably should catch this and return an error message of some kind to the UI saying that the course id could not be found or something. 

```
[2022-05-26 00:02:04 +0000] [ERROR] [log.py:224] Internal Server Error: /api/lti_tools/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/backend/canvas_app_explorer/views.py", line 22, in list
    logger.debug(f"Course ID: {request.session['course_id']}")
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
KeyError: 'course_id'
```

**Comment by ssciolla** [comment]
This is related to #27.

**Comment by zqian** [comment]
How can I repeat the problem? I used the URL format of https://<ngrok url>/api/lti_tools/

- After I launch the tool in Canvas, and I launch the above URL in a separate tab, I got HTTP 200 status.
- If I use Incognito window, I got HTTP 403 with "Authentication credentials were not provided." error

**Comment by jonespm** [comment]
I _think_ it can happen right now if you login to the backend (like as admin) but don't launch it directly. It has the admin credentials but doesn't have the course_id. 

I'm not sure how important it is to fix this without fixing #27, I agree they're related.

**Comment by zqian** [comment]
Got it. I have updated the issue description.

**Comment by zqian** [comment]
Will close this issue based on the latest comment:

From Sam: "Yeah, I think this issue will go away once https://github.com/tl-its-umich-edu/canvas-app-explorer/issues/147 is resolved. I think there's also a separate/side discussion happening here also about how best to implement https://github.com/tl-its-umich-edu/canvas-app-explorer/issues/27. I'm envisioning a separate API view/URL for the public data, rather than branching within this view. We may have to do it that way so we can withhold permission restrictions, since those are applied to the view."
